"""Metadata definitions for THZ sensors.

This module defines the SENSOR_META dictionary, which maps sensor names to their metadata.
Each entry contains information such as data offset, length, decoding method, scaling factor,
units, device class, icon, and translation key (where applicable). This metadata is used to
interpret raw sensor data from THZ devices for integration with Home Assistant.

Example metadata fields:
    - offset: Byte offset in the data stream.
    - length: Number of bytes to read.
    - decode: Method to decode the raw value (e.g., "hex2int", "bit0", "esp_mant").
    - factor: Scaling factor to apply to the decoded value.
    - unit: Unit of measurement (e.g., "°C", "W", "%").
    - device_class: Home Assistant device class (e.g., "temperature", "humidity").
    - icon: Material Design Icon name for UI representation.
    - translation_key: Key for localization (optional).

This structure enables flexible and consistent handling of a wide range of THZ sensor data.
"""

SENSOR_META = {
    "outsideTemp": {
        "offset": 8,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer",
        "translation_key": "outside_temp",
    },
    "flowTemp": {
        "offset": 12,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer",
        "translation_key": "flow_temp",
    },
    "returnTemp": {
        "offset": 16,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer",
        "translation_key": "return_temp",
    },
    "hotGasTemp": {
        "offset": 20,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer",
        "translation_key": "hotgas_temp",
    },
    "dhwTemp": {
        "offset": 24,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:water-boiler",
        "translation_key": "dhw_temp",
    },
    "flowTempHC2": {
        "offset": 28,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:thermometer",
        "translation_key": "flow_temp_hc2",
    },
    "evaporatorTemp": {
        "offset": 36,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:snowflake",
        "translation_key": "evaporator_temp",
    },
    "condenserTemp": {
        "offset": 40,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:radiator",
        "translation_key": "condenser_temp",
    },
    "mixerOpen": {
        "offset": 45,
        "length": 1,
        "decode": "bit0",
        "factor": 1,
        "icon": "mdi:gate-open",
        "translation_key": "mixer_open",
    },
    "mixerClosed": {
        "offset": 45,
        "length": 1,
        "decode": "bit1",
        "factor": 1,
        "icon": "mdi:gate",
        "translation_key": "mixer_closed",
    },
    "heatPipeValve": {
        "offset": 45,
        "length": 1,
        "decode": "bit2",
        "factor": 1,
        "icon": "mdi:valve",
        "translation_key": "heat_pipe_valve",
    },
    "diverterValve": {
        "offset": 45,
        "length": 1,
        "decode": "bit3",
        "factor": 1,
        "icon": "mdi:valve",
        "translation_key": "diverter_valve",
    },
    "dhwPump": {
        "offset": 44,
        "length": 1,
        "decode": "bit0",
        "factor": 1,
        "icon": "mdi:pump",
        "translation_key": "dhw_pump",
    },
    "heatingCircuitPump": {
        "offset": 44,
        "length": 1,
        "decode": "bit1",
        "factor": 1,
        "icon": "mdi:pump",
        "translation_key": "heating_circuit_pump",
    },
    "solarPump": {
        "offset": 44,
        "length": 1,
        "decode": "bit3",
        "factor": 1,
        "icon": "mdi:weather-sunny",
        "translation_key": "solar_pump",
    },
    "compressor": {
        "offset": 47,
        "length": 1,
        "decode": "bit3",
        "factor": 1,
        "icon": "mdi:engine",
        "translation_key": "compressor",
    },
    "boosterStage3": {
        "offset": 46,
        "length": 1,
        "decode": "bit0",
        "factor": 1,
        "translation_key": "booster_stage_3",
    },
    "boosterStage2": {
        "offset": 46,
        "length": 1,
        "decode": "bit1",
        "factor": 1,
        "translation_key": "booster_stage_2",
    },
    "boosterStage1": {
        "offset": 46,
        "length": 1,
        "decode": "bit2",
        "factor": 1,
        "translation_key": "booster_stage_1",
    },
    "highPressureSensor": {
        "offset": 49,
        "length": 1,
        "decode": "nbit0",
        "factor": 1,
        "translation_key": "high_pressure_sensor",
    },
    "lowPressureSensor": {
        "offset": 49,
        "length": 1,
        "decode": "nbit1",
        "factor": 1,
        "translation_key": "low_pressure_sensor",
    },
    "evaporatorIceMonitor": {
        "offset": 49,
        "length": 1,
        "decode": "bit2",
        "factor": 1,
        "translation_key": "evaporator_ice_monitor",
    },
    "signalAnode": {
        "offset": 49,
        "length": 1,
        "decode": "bit3",
        "factor": 1,
        "translation_key": "signal_anode",
    },
    "evuRelease": {
        "offset": 48,
        "length": 1,
        "decode": "bit0",
        "factor": 1,
        "translation_key": "evu_release",
    },
    "ovenFireplace": {
        "offset": 48,
        "length": 1,
        "decode": "bit1",
        "factor": 1,
        "translation_key": "oven_fireplace",
    },
    "STB": {
        "offset": 48,
        "length": 1,
        "decode": "bit2",
        "factor": 1,
        "translation_key": "stb",
    },
    "outputVentilatorPower": {
        "offset": 50,
        "length": 4,
        "decode": "hex",
        "factor": 10,
        "unit": "W",
        "device_class": "power",
        "icon": "mdi:fan",
        "translation_key": "output_ventilator_power",
    },
    "inputVentilatorPower": {
        "offset": 54,
        "length": 4,
        "decode": "hex",
        "factor": 10,
        "unit": "W",
        "device_class": "power",
        "icon": "mdi:fan",
        "translation_key": "input_ventilator_power",
    },
    "mainVentilatorPower": {
        "offset": 58,
        "length": 4,
        "decode": "hex",
        "factor": 10,
        "unit": "W",
        "device_class": "power",
        "icon": "mdi:fan",
        "translation_key": "main_ventilator_power",
    },
    "outputVentilatorSpeed": {
        "offset": 62,
        "length": 4,
        "decode": "hex",
        "factor": 1,
        "unit": "rpm",
        "icon": "mdi:speedometer",
        "translation_key": "output_ventilator_speed",
    },
    "inputVentilatorSpeed": {
        "offset": 66,
        "length": 4,
        "decode": "hex",
        "factor": 1,
        "unit": "rpm",
        "icon": "mdi:speedometer",
        "translation_key": "input_ventilator_speed",
    },
    "mainVentilatorSpeed": {
        "offset": 70,
        "length": 4,
        "decode": "hex",
        "factor": 1,
        "unit": "rpm",
        "icon": "mdi:speedometer",
        "translation_key": "main_ventilator_speed",
    },
    "outside_tempFiltered": {
        "offset": 74,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "icon": "mdi:thermometer",
        "translation_key": "outside_temp_filtered",
    },
    "relHumidity": {
        "offset": 78,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "%",
        "device_class": "humidity",
        "icon": "mdi:water-percent",
        "translation_key": "rel_humidity",
    },
    "dewPoint": {
        "offset": 82,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "icon": "mdi:weather-fog",
        "translation_key": "dew_point",
    },
    "P_Nd": {
        "offset": 86,
        "length": 4,
        "decode": "hex2int",
        "factor": 100,
        "unit": "kW",
        "device_class": "power",
        "icon": "mdi:flash",
        "translation_key": "power_nd",
    },
    "P_Hd": {
        "offset": 90,
        "length": 4,
        "decode": "hex2int",
        "factor": 100,
        "unit": "kW",
        "device_class": "power",
        "icon": "mdi:flash",
        "translation_key": "power_hd",
    },
    "actualPower_Qc": {
        "offset": 94,
        "length": 8,
        "decode": "esp_mant",
        "factor": 1,
        "unit": "kW",
        "device_class": "power",
        "icon": "mdi:flash",
        "translation_key": "actual_power_qc",
    },
    "actualPower_Pel": {
        "offset": 102,
        "length": 8,
        "decode": "esp_mant",
        "factor": 1,
        "unit": "kW",
        "device_class": "power",
        "icon": "mdi:flash",
        "translation_key": "actual_power_pel",
    },
    "collectorTemp": {
        "offset": 4,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:solar-power",
        "translation_key": "collector_temp",
    },
    "insideTemp": {
        "offset": 32,
        "length": 4,
        "decode": "hex2int",
        "factor": 10,
        "unit": "°C",
        "device_class": "temperature",
        "icon": "mdi:home-thermometer",
        "translation_key": "inside_temp",
    },
    "windowOpen": {
        "offset": 47,
        "length": 1,
        "decode": "bit2",
        "factor": 1,
        "icon": "mdi:window-open",
        "translation_key": "window_open",
    },
    "quickAirVent": {
        "offset": 48,
        "length": 1,
        "decode": "bit3",
        "factor": 1,
        "icon": "mdi:fan-speed-3",
        "translation_key": "quick_air_vent",
    },
    "flowRate": {
        "offset": 110,
        "length": 4,
        "decode": "hex2int",
        "factor": 100,
        "unit": "l/min",
        "icon": "mdi:water-pump",
        "translation_key": "flow_rate",
    },
    "p_HCw": {
        "offset": 114,
        "length": 4,
        "decode": "hex",
        "factor": 100,
        "unit": "bar",
        "icon": "mdi:gauge",
        "translation_key": "pressure_hc",
    },
    "humidityAirOut": {
        "offset": 154,
        "length": 4,
        "decode": "hex",
        "factor": 100,
        "unit": "%",
        "device_class": "humidity",
        "icon": "mdi:water-percent",
        "translation_key": "humidity_air_out",
    },
}
